SET FOREIGN_KEY_CHECKS=0
TRUNCATE TABLE TreeAccess;
TRUNCATE TABLE Users;
TRUNCATE TABLE FamilyTrees;
TRUNCATE TABLE Relationships;
TRUNCATE TABLE Marriages;
TRUNCATE TABLE FamilyMembers;
TRUNCATE TABLE ParentChild;
TRUNCATE TABLE SearchHistory;
TRUNCATE TABLE Hobbies;
TRUNCATE TABLE AccessLogs;
SET FOREIGN_KEY_CHECKS=1;